config/routes.rb
Galleries::Application.routes.draw do
  resources :galleries
  resources :images
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	validates :title, :presence => true
	validates :title, :uniqueness => true

	has_friendly_id :title, :use_slug => true
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < InheritedResources::Base
end

app/controllers/images_controller.rb
class ImagesController < InheritedResources::Base

	def new
		new! {
			session = Dropbox::Session.new('g0vvwxw74jq7mqe', '31u7qz5cmw0v46v')
			session.mode = :sandbox
		}
	end

	def create
		create! {
			session = Dropbox::Session.new('g0vvwxw74jq7mqe', '31u7qz5cmw0v46v')
			session.mode = :sandbox
		}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/galleries/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.gallery.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.gallery.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :cached_slug, t("activerecord.attributes.gallery.cached_slug", :default => "Cached slug"), :class => :label %>
    <%= f.text_field :cached_slug, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), galleries_path, :class => "text_button_padding link_button" %>
</div>

app/views/galleries/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", galleries_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_gallery_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_gallery_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Gallery</h2>
    <div class="inner">
      <%= form_for @gallery, :url => gallery_path(@gallery), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/galleries/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", galleries_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_gallery_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Galleries</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.gallery.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @galleries.each do |gallery| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= gallery.id %>
          </td>
                    <td>
            <%= link_to gallery.title, gallery_path(gallery) %>
          </td>
                    <td>
            <%= gallery.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", gallery_path(gallery) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_gallery_path(gallery) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", gallery_path(gallery), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/galleries/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", galleries_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_gallery_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Gallery</h2>
    <div class="inner">
      <%= form_for :gallery, :url => galleries_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/galleries/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", galleries_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_gallery_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", gallery_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.gallery.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @gallery.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.gallery.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @gallery.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.gallery.cached_slug", :default => t("activerecord.labels.cached_slug", :default => "Cached slug")) %>:</b>
          <%= @gallery.cached_slug %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_gallery_path(@gallery), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), gallery_path(@gallery), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/images/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.image.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.image.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
   <%= f.file_field :photo %>
  </div>
 
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), images_path, :class => "text_button_padding link_button" %>
</div>

app/views/images/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/images/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", images_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_image_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_image_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Image</h2>
    <div class="inner">
      <%= form_for @image, :url => image_path(@image), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/images/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", images_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_image_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Images</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.image.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @images.each do |image| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= image.id %>
          </td>
                    <td>
            <%= link_to image.title, image_path(image) %>
          </td>
                    <td>
            <%= image.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", image_path(image) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_image_path(image) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", image_path(image), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/images/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", images_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_image_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Image</h2>
    <div class="inner">
      <%= form_for :image, :url => images_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/images/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", images_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_image_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", image_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.image.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @image.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.image.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @image.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.image.photo_file_name", :default => t("activerecord.labels.photo_file_name", :default => "Photo file name")) %>:</b>
          <%= @image.photo_file_name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.image.photo_content_type", :default => t("activerecord.labels.photo_content_type", :default => "Photo content type")) %>:</b>
          <%= @image.photo_content_type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.image.photo_file_size", :default => t("activerecord.labels.photo_file_size", :default => "Photo file size")) %>:</b>
          <%= @image.photo_file_size %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.image.photo_updated_at", :default => t("activerecord.labels.photo_updated_at", :default => "Photo updated at")) %>:</b>
          <%= @image.photo_updated_at %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_image_path(@image), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), image_path(@image), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galleries</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/galleries.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Web App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>